apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-red
  template:
    metadata:
      labels:
        app: app-red
    spec:
      containers:
      - name: app-red
        image: joaopedrot1912/colors
        env:
          - name: BG_COLOR
            valueFrom:
              secretKeyRef:
                name: color-name-secret
                key: BG_COLOR_RED
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
                